/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.infox.telas;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
import br.com.infox.dal.ModuloConexao; //importa a conexao

/**
 *
 * @author Adm
 */
public class telaEmpresaInicial extends javax.swing.JFrame {

    PreparedStatement pst = null; // smp colocar na tela que ira usar o bacco
    java.sql.Connection conexao = null;// smp colocar na tela que ira usar o bacco
    ResultSet rs = null; //smp colocar na tela que ira usar o bacco EXIBE O RESULTADO DA CONXECAO COM BANCO
    boolean contrato=false;
    /**
     * Creates new form telaEmpresaInicial
     */
    public telaEmpresaInicial() {
        initComponents();
        conexao=ModuloConexao.conector(); // inicia conexao ao abrir o frm
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JTextField();
        lblCnpj = new javax.swing.JTextField();
        lblEmail = new javax.swing.JTextField();
        lblResponsavel = new javax.swing.JTextField();
        lbltelefone = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        rbtLicontrato = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bem Vindo!");

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel1.setText("Bem vindo ao Infox Controle de ordem de serviços.");
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 14));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone hello.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Cadastro De ultilização");

        jLabel4.setText("Empresa:  ");

        jLabel5.setText("Endereço: ");

        jLabel6.setText("CNPJ: ");

        jLabel7.setText("E-mail: ");

        jLabel8.setText("Responsavel: ");

        jLabel9.setText("Telfone de contato: ");

        jLabel10.setText("Contrato: ");

        lblEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblEmpresaActionPerformed(evt);
            }
        });

        lblCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCnpjActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Concessão da Licença:\n2.1 - A LICENCIANTE, neste ato e pela melhor forma de direito, outorga ao LICENCIADO uma licença de\nuso, em caráter não exclusivo e intransferível, para utilização do software.\n2.2 - A licença concedida nos termos deste instrumento é válida somente no Brasil. O LICENCIADO não\nremeterá, transferirá ou exportará de outra forma o produto para fora do território sem a anuência\nprévia por escrito da LICENCIANTE e o pagamento pelo LICENCIADO das eventuais taxas adicionais aos\níndices em vigor da LICENCIANTE.\n2.3 - APLICA-SE A ESTE CONTRATO O DISPOSTO NAS LEIS 9.609/98 (PROTEÇÃO DA PROPRIEDADE\nINTELECTUAL DO SOFTWARE) E 9.610/98 (PROTEÇÃO DOS DIREITOS AUTORAIS);");
        jScrollPane2.setViewportView(jTextArea1);

        rbtLicontrato.setText("Li e concordo com termos acima citados.");
        rbtLicontrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtLicontratoActionPerformed(evt);
            }
        });

        jButton1.setText("Confirmar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltelefone))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResponsavel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblEmpresa))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblEndereco)
                                        .addComponent(lblCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))))
                            .addComponent(jLabel10)
                            .addComponent(rbtLicontrato))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbltelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtLicontrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void entrarTelaPrincipal(){
          
    TelaPrincipal principal = new TelaPrincipal(); //instacia a nova tela a ser aberta
    principal.setVisible(true); //abre nova tela
    TelaPrincipal.relatorioGeral.setEnabled(true);
    TelaPrincipal.MenCadUsu.setEnabled(true);
    TelaPrincipal.lblUsuario.setForeground(Color.red);
    this.dispose(); // fecha tela antiga

    
    }
    public void salvarEmpresaAoEntrar(){
        String sql="insert into tbempresas(nomeemp,endemp,cnpj,email,responsavel,tel,contrato)\n" +
        "values(?,?,?,?,?,?,?)";
        try {
            pst = conexao.prepareStatement(sql);
         
            pst.setString(1, lblEmpresa.getText());
            pst.setString(2, lblEndereco.getText());
            pst.setString(3, lblCnpj.getText());
            pst.setString(4, lblEmail.getText()); 
            pst.setString(5, lblResponsavel.getText());
            pst.setString(6, lbltelefone.getText());
            pst.setBoolean(7, contrato);
            
         
            int adicionado = pst.executeUpdate(); //executa query de atualizacao
            
            //se o valor for maior q zero pq cadastrou
            if (adicionado>0)
            {
               entrarTelaPrincipal();
             
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Erro ao cadastrar nova empresa!"+ e);
        }
        
    }
    private void lblEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEmpresaActionPerformed

    private void lblCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCnpjActionPerformed

    private void rbtLicontratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtLicontratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtLicontratoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(rbtLicontrato.isSelected()&& lblEmpresa.getText()!="" && lblEndereco.getText()!="" && lblCnpj.getText()!="" && lblEmail.getText()!="" && lblResponsavel.getText()!=""){
            contrato=true;
            salvarEmpresaAoEntrar();
            
            
        }else
        {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!!");     
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaEmpresaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaEmpresaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaEmpresaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaEmpresaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaEmpresaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lblCnpj;
    private javax.swing.JTextField lblEmail;
    private javax.swing.JTextField lblEmpresa;
    private javax.swing.JTextField lblEndereco;
    private javax.swing.JTextField lblResponsavel;
    private javax.swing.JTextField lbltelefone;
    private javax.swing.JCheckBox rbtLicontrato;
    // End of variables declaration//GEN-END:variables
}
